"""'update_db'

Revision ID: 16d01728bfb3
Revises: 6b5b9c1e812b
Create Date: 2023-03-05 20:46:43.833278

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16d01728bfb3"
down_revision = "6b5b9c1e812b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    # ### end Alembic commands ###
