"""'create_tokens_table'

Revision ID: 8e374bf55a3f
Revises: 16d01728bfb3
Create Date: 2023-03-05 22:12:12.643690

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e374bf55a3f"
down_revision = "16d01728bfb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
