"""'create_tokens_table'

Revision ID: fe6e1c33d5ed
Revises: 1919611091e7
Create Date: 2023-03-05 22:47:37.012740

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe6e1c33d5ed"
down_revision = "1919611091e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tokens", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tokens", type_="unique")
    # ### end Alembic commands ###
